swagger: "2.0"
info:
  title: task01
  description: API Walk through.
  version: 1.0.0

host: task01.apigateway.mohammed-coe453.cloud.goog
basePath: /
schemes:
  - https
  - http

paths:
  /add:
    post:
      operationId: postAdd
      summary: Open an existing POST running Cloud Function.
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-mohammed-coe453.cloudfunctions.net/add

  /sub:
    post:
      operationId: postSub
      summary: Open an existing POST running Cloud Function.
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-mohammed-coe453.cloudfunctions.net/sub
  /div:
    post:
      operationId: postDiv
      summary: Open an existing POST running Cloud Function.
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-mohammed-coe453.cloudfunctions.net/div

  /mul:
    post:
      operationId: postMul
      summary: Open an existing POST running Cloud Function.
      produces:
        - application/json
      responses:
        200:
          description: OK
      x-google-backend:
        address: https://us-central1-mohammed-coe453.cloudfunctions.net/mul
